=== anaibol/resumes/schema.json
{
   "$schema":"http://json-schema.org/draft-04/schema#",
   "title":"Resume Schema",
   "type":"object",
   "additionalProperties":false,
   "properties":{
      "basics":{
         "type":"object",
         "additionalProperties":false,
         "properties":{
            "name":{
               "type":"string",
               "description":"e.g. Juan Micheli"
            },
            "label":{
               "type":"string",
               "description":"e.g. Web Developer"
            },
            "email":{
               "type":"string",
               "description":"e.g. hey@anib.al",
               "format":"email"
            },
            "phone":{
               "type":"string",
               "description":"e.g.  +33 06 8994 0397 (use any format you like)"
            },
            "website":{
               "type":"string",
               "description":"URL to your website, e.g. http://anib.al",
               "format":"uri"
            },
            "summary":{
               "type":"string",
               "description":"Write a short 2-3 sentence biography about yourself"
            },
            "location":{
               "type":"object",
               "additionalProperties": false,
               "properties": {
                  "postalCode":{
                     "type":"string"
                  },
                  "city":{
                     "type":"string"
                  }
               },
               "required": ["city", "postalCode"]
            },
            "profiles":{
               "type":"array",
               "description":"Specify any number of profiles",
               "additionalItems":false,
               "items":{
                  "type":"object",
                  "additionalProperties":false,
                  "properties":{
                     "network":{
                        "type":"string",
                        "description":"e.g. Github profile"
                     },
                     "username":{
                        "type":"string",
                        "description":"e.g. anaibol"
                     },
                     "url":{
                        "type":"string",
                        "description":"e.g. http://github.com/anaibol"
                     }
                  }
               }
            }
         },
         "required": ["name", "label", "email", "summary"]
      },
      "works":{
         "type":"array",
         "additionalItems":false,
         "items":{
            "type":"object",
            "additionalProperties":false,
            "properties":{
               "company":{
                  "type":"string",
                  "description":"e.g. Facebook"
               },
               "position":{
                  "type":"string",
                  "description":"e.g. Software Engineer"
               },
               "website":{
                  "type":"string",
                  "description":"e.g. http://facebook.com",
                  "format":"uri"
               },
               "logo":{
                  "type":"string",
                  "description":"e.g. http://facebook.com/images/logo.png",
                  "format":"uri"
               },
               "startDate":{
                  "type":"string",
                  "description":"e.g. 2014-06-29",
                  "format":"date"
               },
               "endDate":{
                  "type":"string",
                  "description":"e.g. 2012-06-29",
                  "format":"date"
               },
               "summary":{
                  "type":"string",
                  "description":"Give an overview of your responsibilities at the company"
               },
               "skills":{
                  "type":"object",
                  "description":"Specify multiple accomplishments",
                  "additionalItems":false,
                  "properties":{
                     "organization":{
                        "type":"string",
                        "description":"e.g. Facebook"
                     },
                     "position":{
                        "type":"string",
                        "description":"e.g. Software Engineer"
                     }
                  }
               },
               "highlights":{
                  "type":"array",
                  "description":"Specify multiple accomplishments",
                  "additionalItems":false,
                  "items":{
                     "type":"string",
                     "description":"e.g. Increased profits by 20% from 2011-2012 through viral advertising"
                  }
               }
            }
         }
      },
      "volunteer":{
         "type":"array",
         "additionalItems":false,
         "items":{
            "type":"object",
            "additionalProperties":false,
            "properties":{
               "organization":{
                  "type":"string",
                  "description":"e.g. Greenpeace"
               },
               "position":{
                  "type":"string",
                  "description":"e.g. Software Engineer"
               },
               "website":{
                  "type":"string",
                  "description":"e.g. http://greenpeace.com",
                  "format":"uri"
               },
               "startDate":{
                  "type":"string",
                  "description":"e.g. 2014-06-29",
                  "format":"date"
               },
               "endDate":{
                  "type":"string",
                  "description":"e.g. 2012-06-29",
                  "format":"date"
               },
               "summary":{
                  "type":"string",
                  "description":"Give an overview of your responsibilities at the company"
               },
               "highlights":{
                  "type":"array",
                  "description":"Specify multiple accomplishments",
                  "additionalItems":false,
                  "items":{
                     "type":"string",
                     "description":"e.g. Increased profits by 20% from 2011-2012 through viral advertising"
                  }
               }
            }
         }
      },
      "education":{
         "type":"array",
         "additionalItems":false,
         "items":{
            "type":"object",
            "additionalProperties":false,
            "properties":{
               "institution":{
                  "type":"string",
                  "description":"e.g. Massachusetts Institute of Technology"
               },
               "area":{
                  "type":"string",
                  "description":"e.g. Arts"
               },
               "studyType":{
                  "type":"string",
                  "description":"e.g. Bachelor"
               },
               "startDate":{
                  "type":"string",
                  "description":"e.g. 2014-06-29",
                  "format":"date"
               },
               "endDate":{
                  "type":"string",
                  "description":"e.g. 2012-06-29",
                  "format":"date"
               },
               "gpa":{
                  "type":"string",
                  "description":"grade point average, e.g. 3.67/4.0"
               },
               "courses":{
                  "type":"array",
                  "description":"List notable courses/subjects",
                  "additionalItems":false,
                  "items":{
                     "type":"string",
                     "description":"e.g. H1302 - Introduction to American history"
                  }
               }
            }
         }
      },
      "awards":{
         "type":"array",
         "description":"Specify any awards you have received throughout your professional career",
         "additionalItems":false,
         "items":{
            "type":"object",
            "additionalProperties":false,
            "properties":{
               "title":{
                  "type":"string",
                  "description":"e.g. One of the 100 greatest minds of the century"
               },
               "date":{
                  "type":"string",
                  "description":"e.g. 1989-06-12",
                  "format":"date"
               },
               "awarder":{
                  "type":"string",
                  "description":"e.g. Time Magazine"
               },
               "summary":{
                  "type":"string",
                  "description":"e.g. Received for my work with Quantum Physics"
               }
            }
         }
      },
      "publications":{
         "type":"array",
         "description":"Specify your publications through your career",
         "additionalItems":false,
         "items":{
            "type":"object",
            "additionalProperties":false,
            "properties":{
               "name":{
                  "type":"string",
                  "description":"e.g. The World Wide Web"
               },
               "publisher":{
                  "type":"string",
                  "description":"e.g. IEEE, Computer Magazine"
               },
               "releaseDate":{
                  "type":"string",
                  "description":"e.g. 1990-08-01"
               },
               "website":{
                  "type":"string",
                  "description":"e.g. http://www.computer.org/csdl/mags/co/1996/10/rx069-abs.html"
               },
               "summary":{
                  "type":"string",
                  "description":"Short summary of publication. e.g. Discussion of the World Wide Web, HTTP, HTML."
               }
            }
         }
      },
      "skills":{
         "type":"array",
         "description":"List out your professional skill-set",
         "additionalItems":false,
         "items":{
            "type":"object",
            "additionalProperties":false,
            "properties":{
               "name":{
                  "type":"string",
                  "description":"e.g. Web Development"
               },
               "level":{
                  "type":"string",
                  "description":"e.g. Master"
               },
               "keywords":{
                  "type":"array",
                  "description":"List some keywords pertaining to this skill",
                  "additionalItems":false,
                  "items":{
                     "type":"string",
                     "description":"e.g. HTML"
                  }
               }
            }
         }
      },
      "languages":{
         "type":"array",
         "description":"List any other languages you speak",
         "additionalItems":false,
         "items":{
            "type":"object",
            "additionalProperties":false,
            "properties":{
               "language":{
                  "type":"string",
                  "description":"e.g. English, Spanish"
               },
               "fluency":{
                  "type":"string",
                  "description":"e.g. Fluent, Beginner"
               }
            }
         }
      },
      "interests":{
         "type":"array",
         "additionalItems":false,
         "items":{
            "type":"object",
            "additionalProperties":false,
            "properties":{
               "name":{
                  "type":"string",
                  "description":"e.g. Philosophy"
               },
               "keywords":{
                  "type":"array",
                  "additionalItems":false,
                  "items":{
                     "type":"string",
                     "description":"e.g. Friedrich Nietzsche"
                  }
               }
            }
         }
      },
      "references":{
         "type":"array",
         "description":"List references you have received",
         "additionalItems":false,
         "items":{
            "type":"object",
            "additionalProperties":false,
            "properties":{
               "name":{
                  "type":"string",
                  "description":"e.g. Timothy Cook"
               },
               "reference":{
                  "type":"string",
                  "description":"e.g. Joe blogs was a great employee, who turned up to work at least once a week. He exceeded my expectations when it came to doing nothing."
               }
            }
         }
      }
   }
}

=== anaibol/resumes/resumes/juan-anibal-micheli.json
{
  "basics": {
    "name": "Juan Anibal Micheli",
    "label": "Fullstack Javascript Engineer",
    "email": "hey@anib.al",
    "phone": "(912) 555-4321",
    "website": "http://anib.al",
    "summary": "I am a creative, dynamic, curious, prolific web developer. I like feeling comfortable with the entire stack needed for a web project, from layout and client-side application structure, to backend development and server infrastructure. I am always pursuing new technologies, frameworks and libraries, and I believe web technologies will be soon a multi-platform standard, used for common mobile apps and even for programming robots! And of course, I am in love with Javascript :)",
    "location": {
      "city": "Paris",
      "postalCode": "93241"
    },
    "profiles": [
      {
        "network": "Twitter",
        "username": "neutralthoughts",
        "url": "http://github.com/anaibol/"
      },
      {
        "network": "Github",
        "username": "anaibolll",
        "url": "http://github.com/anaibol"
      }
    ]
  },
  "works": [
    {
      "company": "abbeal",
      "position": "Fullstack Javascript Contractor",
      "website": "http://abbeal.com",
      "logo": "https://media.licdn.com/media/AAEAAQAAAAAAAAN5AAAAJDZkNWEzMzYwLTcwYzYtNDRlZS1iZDIzLWRiNmZkOTU4ZGFiMQ.png",
      "startDate": "2015-01-10",
      "summary": "ES6/ES7, Redux, React, NodeJS, ExpressJS, React Router, lazy-loading (chunks), critical rendering path",
      "highlights": [],
      "skills": {
        "Languages": [
          "Javascript",
          "PHP"
        ],
        "Tests": [],
        "Frameworks, CMS-API": [
          "AngularJS"
        ],
        "Servers": [],
        "Continuous Integration": [],
        "IDE": [
          "Sublime Text 2"
        ]
      },
      "endDate": "2016-01-10"
    },
    {
      "company": "Wooepa SAS France",
      "position": "Freelance Fullstack Engineer (MEAN stack)",
      "website": "http://wooepa.com",
      "startDate": "2013-01-02",
      "endDate": "2015-01-03",
      "summary": "Built an event promotion platform from scratch using MongoDB, ExpressJS, AngularJS and Node.js.\nChoice of technologies, decision taking, devising.\nA lot of interaction with Facebook API (Graph API, FQL, invitations, RSVP..). SEO, web scraping, geospatial search, frontend performance optimization, POC with Polymer.",
      "highlights": [],
      "skills": {
        "Languages": [
          "Javascript",
          "PHP"
        ],
        "Tests": [],
        "Frameworks, CMS-API": [
          "Zend"
        ],
        "Servers": [],
        "Continuous Integration": [],
        "IDE": [
          "Webstorm"
        ]
      }
    },
    {
      "company": "HINCH.AS",
      "position": "Javascript Engineer (AngularJS)",
      "website": "http://hinch.as",
      "startDate": "2015-02-05",
      "summary": "Built an admin panel for administrating the main site entities. I used AngularJS and Bootstrap UI communicating with a RPC-JSON API with JWT based authentification.",
      "skills": {
        "Languages": [
          "Javascript",
          "PHP"
        ],
        "Tests": [],
        "Frameworks, CMS-API": [
          "AngularJS"
        ],
        "Servers": [],
        "Continuous Integration": [],
        "IDE": [
          "Sublime Text 2"
        ]
      },
      "highlights": [
        "Build an algorithm for artist to detect if their music was violating copy right infringement laws",
        "Successfully won Techcrunch Disrupt",
        "Optimized an algorithm that holds the current world record for Weisman Scores"
      ],
      "endDate": "2015-07-05"
    },
    {
      "company": "FWTV",
      "position": "Web Developer",
      "website": "http://fwtv.tv",
      "logo": "http://fwtv.tv",
      "startDate": "2013-01-01",
      "endDate": "2013-03-01",
      "summary": "PHP, Symfony2, MySQL, Elastic Search, Redis, agile development.\nDigital TV channel, music and sport fans.\nI worked with Symfony2, a great PHP MVC framework, with Doctrine ORM, implemented Elasticsearch for indexing the entities and search them, and Redis for caching DB queries and with Nginx proxy for caching webpages.",
      "highlights": []
    },
    {
      "company": "Hoopla",
      "position": "Web Developer (PHP, Node.js, Magento)",
      "website": "http://hoopla.la",
      "logo": "http://hoopla.la",
      "startDate": "2012-01-01",
      "endDate": "2013-04-01",
      "summary": "PHP, NodeJS, Mongodb, MySQL, JQuery, Magento, social API's and some Magento e-commerce.\nI worked in several little (2 weeks) projects, pressure and innovation in a digital agency.",
      "highlights": []
    },
    {
      "company": "FriendBall.net",
      "position": "Web Developer (PHP, Zend framework, MySQL, Frontend and Backend development)",
      "website": "http://friendball.net",
      "logo": "http://friendball.net",
      "startDate": "2012-01-01",
      "endDate": "2012-05-01",
      "summary": "PHP, Zend framework, OAuth, Facebook API\nFootball social network.\nFacebook integration, chat, mail invitations, frontend and backend development.",
      "highlights": []
    },
    {
      "company": "Pragmore",
      "position": "Web Developer (PHP, Symfony, MySQL, HTML5, CSS3, Frontend and Backend development)",
      "website": "http://pragmore.com",
      "logo": "http://pragmore.com",
      "startDate": "2010-01-01",
      "endDate": "2012-01-02",
      "summary": "Symfony, MySQL\nSeveral projects, rapid web development, Symfony 1.2 - 1.4, Doctrine, Mysql. Layout & backend development.",
      "highlights": []
    }
  ],
  "volunteer": [
    {
      "organization": "CoderDojo",
      "position": "Teacher",
      "website": "http://coderdojo.com/",
      "startDate": "2012-01-01",
      "endDate": "2013-05-01",
      "summary": "Global movement of free coding clubs for young people.",
      "highlights": [
        "Awarded 'Teacher of the Month'"
      ]
    }
  ],
  "education": [
    {
      "institution": "Lyc√©e franco-argentin Jean Mermoz",
      "area": "",
      "studyType": "French and Argentinian Bachelor's degrees",
      "startDate": "1992-01-01",
      "endDate": "2008-05-01",
      "gpa": "",
      "courses": []
    }
  ],
  "awards": [
    {
      "title": "Digital Compression Pioneer Award",
      "date": "2014-11-01",
      "awarder": "Techcrunch",
      "summary": "There is no spoon."
    }
  ],
  "publications": [
    {
      "name": "Video compression for 3d media",
      "publisher": "Hooli",
      "releaseDate": "2014-10-02",
      "website": "http://en.wikipedia.org/wiki/Silicon_Valley_(TV_series)",
      "summary": "Innovative middle-out compression algorithm that changes the way we store data."
    }
  ],
  "languages": [
    {
      "language": "English",
      "fluency": "Intermediate"
    },
    {
      "language": "French",
      "fluency": "Intermediate"
    },
    {
      "language": "Spanish",
      "fluency": "Intermediate"
    }
  ],
  "interests": [
    {
      "name": "Wildlife",
      "keywords": [
        "Ferrets",
        "Unicorns"
      ]
    }
  ],
  "references": [
    {
      "name": "Erlich Bachmanssn",
      "reference": "It is my pleasure to recommend Richard, his performance working as a consultant for Main St. Company proved that he will be a valuable addition to any company.ss"
    }
  ]
}
